### PR TITLE
minor fix orm.rst

### PR DESCRIPTION
**Pull request by fbertolotti**

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Not sure if this should be fixed, I think we use `\` everywhere.

**Comment by dbu** [comment]
afaik in .rst source code is double backtick (the ` character). if you use those, the single backslash should be fine.

**Comment by kunicmarko20** [comment]
Just checked rest of docs and you are correct, @fbertolotti could you change it to double backtick and with jus tone backslash.

**Comment by fbertolotti** [comment]
I've updated it :)

**Comment by greg0ire** [comment]
To be squash merged

**Comment by greg0ire** [comment]
Thanks @fbertolotti !

**Pull request merged**
