### PR TITLE
#66 : Feature : add locale switcher on show action

### LINKED ISSUE #66: Feature : add locale switcher on show action
Right now this bundle only works on edit form.

We need to add this on show screen for users who only have view access

### PR DESCRIPTION
**Pull request by nicolas-bastien**
Fix #66

### CODE REVIEW

**Comment by OskarStark** [comment]
do you have a screenshot @nicolas-bastien ?

**Comment by nicolas-bastien** [comment]
@OskarStark Local switcher block is displayed the same way as edit.

There is no flag on each translated elements.
sonatatransaltionbundle-show-actions

CS is green now. Do you have something else to check or can we merge ?

**Comment by OskarStark** [comment]
cool :+1: 

no i like this, please merge this!

**Comment by nicolas-bastien** [comment]
@OskarStark in next PR I'll make this works for custom action, I'll add some doc.
Would be great if you can give me feedback I'll push that tomorrow

**Comment by OskarStark** [comment]
of course, ping me @nicolas-bastien :+1:

**Pull request merged**
