### PR TITLE
Prepare 1.0.0 release

### PR DESCRIPTION
**Pull request by nicolas-bastien**

### CODE REVIEW

**Comment by rande** [comment]
@nicolas-bastien I think the 1.0.0 should use the old ErrorEelement

**Comment by rande** [comment]
the 2.0.0 should use the new version ;)

**Comment by nicolas-bastien** [comment]
Hi @rande,

We spoke about it a long time ago.
I'd like to tag before merging the next PR, stil ok with this versionning ?

**Comment by nicolas-bastien** [comment]
ok you're too fast !

**Pull request merged**
