### PR TITLE
Updated composer to support 3.0 symfony version

### PR DESCRIPTION
**Pull request by andrewtch**
Subj; confirmed to work w/o further modifications.

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @rande

**Comment by andrewtch** [comment]
let's annoy @rande  together )

**Comment by nicolas-bastien** [comment]
Hi I think we can resolve this together.

SonataAdmin already moved this way so we can go to.

Can we wait a few days so I can a version before ?
But I need to fix some doc before

**Comment by andrewtch** [comment]
@nicolas-bastien , take your time, just don't forget to merge it )

**Comment by OskarStark** [comment]
> take your time, just don't forget to merge it )

:smile:

**Comment by andrewtch** [comment]
Not funny, I has a PR on Twig about "fake" caching that Fabien merged after 1.5 years ))

**Comment by OskarStark** [comment]
this i long...

**Comment by OskarStark** [comment]
but keep in mind... good code takes a while .... :smile: 

just kidding

**Comment by core23** [comment]
@andrewtch Can you please update travis?

**Comment by core23** [comment]
Btw. I think we can drop Symfony 2.2 too

**Comment by andrewtch** [comment]
Em, @core23 , update actually how?...

Remove "3.0 as 2.8"?

**Comment by core23** [comment]
I was thinking about something like https://github.com/sonata-project/SonataAdminBundle/blob/master/.travis.yml

Symfony 3.0 could be removed from about failures.

**Comment by andrewtch** [comment]
Guys, by the time you review my PR I manage to fix all the issues differently )

Anyway, I've pushed something but the travis broke (wow. wasn't me this time). I'll check this tomorrow and squash commits if it works.

**Comment by andrewtch** [comment]
Ok, @core23 , it works, i've added 7.0 tests and removed php deprecation check accordingly.

By the way, maybe we should remove 7.0 from failures also since it builds ok (the current failure is network problem with composer)?

**Comment by core23** [comment]
There is a general talk for the version management https://github.com/sonata-project/SonataCoreBundle/pull/227

Please be patient

**Comment by andrewtch** [comment]
Soooo.... what shoud we do with this?

**Comment by core23** [comment]
I merge this for now, but we should update this soon

**Pull request merged**
