### PR TITLE
Move framework bundle to require section

### PR DESCRIPTION
**Pull request by VincentLanglet**
Solving https://github.com/sonata-project/SonataTranslationBundle/pull/585#issuecomment-986302424

### CODE REVIEW

**Review by jordisala1991 — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
UserLocaleSubscriber is using
```
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Http\Event\InteractiveLoginEvent;
use Symfony\Component\Security\Http\SecurityEvents;
```

And there is also 
```
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
```

So I added them.

**Review by jordisala1991 — DISMISSED** [review]

**Comment by franmomu** [comment]
I'll try to take a look tomorrow, but I think we can get rid of some event listeners

**Comment by VincentLanglet** [comment]
I need to update the PR since https://github.com/sonata-project/SonataTranslationBundle/pull/599 will remove some dependencies

**Comment by VincentLanglet** [comment]
This and https://github.com/sonata-project/SonataTranslationBundle/pull/599 are ready to be merged @sonata-project/contributors

**Review by franmomu — APPROVED** [review]

**Comment by franmomu** [comment]
thanks @VincentLanglet!

**Pull request merged**
