### PR TITLE
DevKit updates for 2.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by dmarkowicz** [comment]
Build failed because since #186 it use SonataDoctrineORMAdminBundle for tests. But there is no tagged release with https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/732 yet.

**Comment by greg0ire** [comment]
Thanks! @soullivaneuh please tag a release

**Comment by greg0ire** [comment]
Are you sure about this @dmarkowicz ? The build is only failing on prefer lowest.

**Comment by greg0ire** [comment]
Found the actual blocker.

**Pull request merged**
