### PR TITLE
Resolve next major comments

### PR DESCRIPTION
**Pull request by franmomu**

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks

**Comment by VincentLanglet** [comment]
What is missing to release the stable (or the RC) version now ? @franmomu (cc @jordisala1991)

**Comment by jordisala1991** [comment]
Would be nice to give a last look at:

- ~~phpstan / psalm~~ Probably ok
- ~~deprecations~~ Probably ok
- composer.json (missing at least framework bundle)
- docs
- last bug report (also reported on admin bundle in a different way)

**Comment by VincentLanglet** [comment]
https://github.com/sonata-project/SonataTranslationBundle/pull/596 for the doc

**Comment by VincentLanglet** [comment]
And framework bundle is here: https://github.com/sonata-project/SonataTranslationBundle/blob/3.x/composer.json#L56

**Comment by jordisala1991** [comment]
It is on require dev, but this is mainly a bundle so it makes more sense to be on require

**Pull request merged**
