### PR TITLE
Allow support PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Added
- Add support for PHP 8.0
```

### CODE REVIEW

**Comment by OskarStark** [comment]
@Yozhef I updated the PR header, please keep this markup, otherwise our tools cannot generate the changelog. Thanks 👍

**Comment by Yozhef** [comment]
Blocked by https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1285

**Comment by erik-zicht** [comment]
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1285 has been merged, if we run the tests again, will they pass?

**Comment by jordisala1991** [comment]
We should remove this bundle first: https://github.com/stof/StofDoctrineExtensionsBundle/issues/422

Do we have any usage in code?

**Comment by franmomu** [comment]
> We should remove this bundle first: [stof/StofDoctrineExtensionsBundle#422](https://github.com/stof/StofDoctrineExtensionsBundle/issues/422)
> 
> Do we have any usage in code?

Yes: https://github.com/sonata-project/SonataTranslationBundle/search?q=stof

IMO we could add a `translatable_listener_service` key [to gedmo configuration](https://github.com/sonata-project/SonataTranslationBundle/blob/bd24ccb799565ebbb465f3853b4d0a136e4d7541/src/DependencyInjection/Configuration.php#L49) that triggers a deprecation if it is not set and by default set it to `stof_doctrine_extensions.listener.translatable` and then create the alias of that service in https://github.com/sonata-project/SonataTranslationBundle/blob/0dd84854886ea3803afc0c054b38b0a4c02b485f/src/Resources/config/service_gedmo.xml#L14.

I'll see if I can find time to do it maybe this night.

**Comment by jordisala1991** [comment]
If you rebase it should be green now

**Review by jordisala1991 — APPROVED** [review]
Or maybe it is not necessary to rebase, can you please create the dev kit Pr? @Yozhef

**Comment by Yozhef** [comment]
@jordisala1991 https://github.com/sonata-project/dev-kit/pull/1434 - done =)

**Pull request merged**
