### PR TITLE
Allow to install latest version of sonata packages

### PR DESCRIPTION
**Pull request by franmomu**
Allows `sonata-project/admin-bundle` 4.x
Allows `sonata-project/doctrine-orm-admin-bundle` 4.x

- [x] [Update dev-kit](https://github.com/sonata-project/dev-kit/pull/1148)

### CODE REVIEW

**Comment by VincentLanglet** [comment]
image
This is weird

**Comment by franmomu** [comment]
> image
> This is weird

Apparently is because the branch [was configured to those checks.](https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157)

**Comment by jordisala1991** [comment]
> > image
> 
> > This is weird
> 
> 
> 
> Apparently is because the branch [was configured to those checks.](https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157) 

Yes, you need to remove that version from dev-kit config first (maybe we can remove php 7.2 from every master branch if not already removed)

**Comment by OskarStark** [comment]
Merged the dev-kit PR, dispatched here: https://github.com/sonata-project/SonataTranslationBundle/pull/387

**Review by OskarStark — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks 👍

**Pull request merged**
