### PR TITLE
[PHPCR] Make it possible to create new languages of a document

### PR DESCRIPTION
**Pull request by WouterJ**
Currently, it is impossible to add a new translation of a document using the admin fields. With this patch, adding new translations is possible.

Fixes https://github.com/symfony-cmf/cmf-sandbox/issues/323

### CODE REVIEW

**Comment by maity-kgz** [comment]
@WouterJ This patch fixes the issue partially. I.e its actually create new translation and saves to db.
But user interface still is not clear. When you trying to add translation to existing document it is hard to determine what language you are adding. (you can determine current language only by looking to URL in address bar). Highlighted flag is wrong, it is fallback to original language flag.
Issue affects only existing documents.
Creating new document is OK, flags highlighted correctly until you save and try to add other language.

**Comment by WouterJ** [comment]
Thanks for the testing @maity-kgz. I've now changed the code to simply `findTranslation()` + `bindTranslation()` (to set the locale field). It seems to work correctly on my side.

@dbu can you maybe quickly validate this? There was a comment saying this didn't work, but I think they used `bindTranslation` only (without `findTranslation`).

**Comment by maity-kgz** [comment]
@WouterJ  :+1:

**Comment by WouterJ** [comment]
Is anyone maintaining this bundle and willing to merge this fix and create a new release?

**Comment by dbu** [comment]
i am not exactly a maintainer of this, but allowed to merge and the PHPCR part indeed works like this. thanks a lot wouter!

**Pull request merged**
