### PR TITLE
Drop SonataCoreBundle

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

I am targeting this branch, because it its BC-~~break~~.

## Changelog

```markdown
### Removed
- Removed `SonataCoreBundle` 
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> I am targeting this branch, because it its BC-break.

Why ?

**Comment by wbloszyk** [comment]
> > I am targeting this branch, because it its BC-break.
> 
> Why ?

Becouse It replace SonataCoreBundle to extensions packkages. They are in conflict, so You can not use both. User must upgrade bundles (like admin) by major version.

**Comment by VincentLanglet** [comment]
> > > I am targeting this branch, because it its BC-break.
> > 
> > 
> > Why ?
> 
> Becouse It replace SonataCoreBundle to extensions packages. They are in conflict, so You can not use both. User must upgrade bundles (like admin) by major version.

IMO, if you're just dropping a dependency, this is not a BC-break, since composer will resolve the right version to use for the user depending on the constraint.
But maybe I'm wrong.

**Comment by phansys** [comment]
If none of the features provided by the removed package are used in this package, there is no BC break at all.

**Comment by wbloszyk** [comment]
My bad, you have right. I change branch from master to 2.x.

**Comment by phansys** [comment]
[Travis is passing](https://travis-ci.org/github/sonata-project/SonataTranslationBundle/builds/667596315?), but no reporting (yet).

**Comment by greg0ire** [comment]
Thanks @wbloszyk !

**Pull request merged**
