### PR TITLE
2.x into Master

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Review by wbloszyk — DISMISSED** [review]
IMO we should not increase phpstan level in master yet.

**Comment by VincentLanglet** [comment]
> IMO we should not increase phpstan level in master yet.

This was increased in 3.x

**Comment by wbloszyk** [comment]
> > IMO we should not increase phpstan level in master yet.
> 
> This was increased in 3.x

I know. It should be inrease in seperate PR. Master have change with is no compatybile wih `max` level. 
Or we can ignore it in here to not awaiting for merge.

**Comment by VincentLanglet** [comment]
> > > IMO we should not increase phpstan level in master yet.
> > 
> > 
> > This was increased in 3.x
> 
> I know. It should be inrease in seperate PR. Master have change with is no compatybile wih `max` level.
> Or we can ignore it in here to not awaiting for merge.

That's not an issue to fix the new static analysis error on master, like I did.
See, the test are green now.

**Review by wbloszyk — APPROVED** [review]

**Pull request merged**
