### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by OskarStark**
Fix build

### CODE REVIEW

**Comment by greg0ire** [comment]
The prefer-lowest job fails:
> PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /home/travis/build/sonata-project/SonataTranslationBundle/vendor/symfony/framework-bundle/Test/KernelTestCase.php on line 23

Looks like you have to bump the framework bundle too.

**Comment by OskarStark** [comment]
I did this, but this doesn't work:

```diff
- "symfony/framework-bundle": "^2.8 || ^3.2 || ^4.0",
+ "symfony/framework-bundle": "^3.2 || ^4.0",
```

**Comment by greg0ire** [comment]
@OskarStark try `3.2.5`

**Comment by OskarStark** [comment]
you mean:

I did this, but this doesn't work:

```diff
- "symfony/framework-bundle": "^2.8 || ^3.2 || ^4.0",
+ "symfony/framework-bundle": "^3.2.5 || ^4.0",
```
?

**Comment by greg0ire** [comment]
It really should

**Comment by greg0ire** [comment]
Maybe it cannot install 3, installed 4.0.0 and this needs to be bumped too? Did the error message change?

**Comment by greg0ire** [comment]
Ah I managed to view the error message from my phone, really weird

**Comment by OskarStark** [comment]
Yes it changed:
`
 [Composer\DependencyResolver\SolverProblemsException]                                                                                                      
  Problem 1                                                                                                                                                  
      - The requested package symfony/framework-bundle ^3.2.5 || ^4.0 exists as symfony/framework-bundle[v2.8.0] but these are rejected by your constraint. 
`

maybe this is required by another dependency?

**Comment by greg0ire** [comment]
Lol have a look in the require dev section

**Comment by OskarStark** [comment]
> Lol have a look in the require dev section

argh... why do we have this there? oO

**Comment by greg0ire** [comment]
Apparently the right place for this is `require-dev`: see #210

**Comment by greg0ire** [comment]
The build shows that you need now to bump the core bundle

**Comment by greg0ire** [comment]
Damned, there is no release containing the commit we need: https://github.com/sonata-project/SonataCoreBundle/commit/7d7151280c3db3906872af2683c4e2ce590fe660

**Comment by greg0ire** [comment]
Please try with sonata core 3.12

**Comment by OskarStark** [comment]
I rearranged my commits, so we can do a Rebase-Merge

Thanks for your help @greg0ire 🍰

**Comment by greg0ire** [comment]
Sorry, I had network issues :P

**Pull request merged**
